version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}

  pdfbox:
    image: elchubi/pdfbox
    container_name: pdfbox
    volumes:
      - ./uploads:/app/uploads
    # entrypoint: ["java", "-jar", "/tmp/pdfbox-app-1.8.11.jar", "ExtractText"]
    entrypoint: ["tail", "-f", "/dev/null"]